config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "welcome#index"

  resources :users, only: [:new, :create, :show], shallow: true do
    resources :ideas
  end

  namespace :admin do
    resources :categories
    resources :images, except: [:show]
  end

  get "/login", to: "sessions#new"
  post "/login", to: "sessions#create"
  delete "/logout", to: "sessions#destroy"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  validates_presence_of :title
  has_many :ideas, dependent: :destroy
end

app/models/idea.rb
class Idea < ApplicationRecord
  validates_presence_of :title,
                        :content
  belongs_to :user
  belongs_to :category
  has_many :idea_images
  has_many :images, through: :idea_images
end

app/models/idea_image.rb
class IdeaImage < ApplicationRecord
  belongs_to :idea
  belongs_to :image
end

app/models/image.rb
class Image < ApplicationRecord
  validates_presence_of :url
  has_many :idea_images, dependent: :destroy
  has_many :ideas, through: :idea_images
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  validates_presence_of   :username,
                          :password
  validates_uniqueness_of :username
  has_many :ideas

  enum role: %w(default admin)
end

app/controllers/admin/base_controller.rb
class Admin::BaseController < ApplicationController
  before_action :require_admin

  private

    def require_admin
      render file: "/public/404" unless current_admin?
    end
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseController
  def index
    @categories = Category.all
    @user = current_user
  end

  def new
    @category = Category.new
    @user = current_user
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "#{@category.title} successfully created"
      redirect_to admin_category_path(@category)
    else
      flash[:error] = "#{@category.title} not saved. try again?"
      render :new
    end
  end

  def show
    @category = Category.find(params[:id])
    @user = current_user
  end

  def edit
    @category = Category.find(params[:id])
    @user = current_user
  end

  def update
    @category = Category.find(params[:id])
    if @category.update(category_params)
      flash[:success] = "#{@category.title} successfully Updated."
      redirect_to admin_category_path(@category)
    else
      flash[:error] = "Something went wrong. Try again?"
      render :edit
    end
  end

  def destroy
    @category = Category.find(params[:id])
    if @category.destroy
      flash[:success] = "Category Deleted"
      redirect_to admin_categories_path
    else
      flash[:error] = "Category was not Deleted. Try again?"
      render admin_categories_path
    end
  end

  private

    def category_params
      params.require(:category).permit(:title)
    end
end

app/controllers/admin/images_controller.rb
class Admin::ImagesController < Admin::BaseController

  def index
    @images = Image.all
    @user = current_user
  end

  def new
    @image = Image.new
    @user = current_user
  end

  def create
    @image = Image.new(image_params)
    if @image.save
      flash[:success] = "Image successfully Saved."
      redirect_to admin_images_path
    else
      render :new
    end
  end

  def edit
    @image = Image.find(params[:id])
    @user = current_user
  end

  def update
    @image = Image.find(params[:id])
    if @image.update(image_params)
      flash[:success] = "Image successfully Edited."
      redirect_to admin_images_path
    else
      flash[:error] = "Something went wrong. Try again?"
      render :edit
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.idea_images.destroy_all
    if @image.destroy
      redirect_to admin_images_path
    else
      render :edit
    end
  end

  private

    def image_params
      params.require(:image).permit(:url)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def current_admin?
    current_user && current_user.admin?
  end

  def require_user
    render file: "/public/404" unless current_user
  end
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :require_user
  before_action :which_user, except: [:create]
  before_action :which_idea, only: [:show, :edit, :update, :destroy]
  def index
    @ideas = @user.ideas
  end

  def new
    @categories = Category.all
    @images = Image.all
    @idea = @user.ideas.new
  end

  def create
    @user = User.find(params[:user_id])
    @idea = @user.ideas.new(idea_params)
    set_images
    if @idea.save
      flash[:success] = "Idea Saved"
      redirect_to user_ideas_path
    else
      flash[:error] = "Something went wrong."
      render :new
    end
  end

  def show
  end

  def edit
    @categories = Category.all
    @images = Image.all
  end

  def update
    @idea.idea_images.destroy_all
    set_images
    if @idea.update(idea_params)
      flash[:success] = "#{@idea.title} was Updated."
      redirect_to idea_path(@idea)
    else
      render :edit
    end
  end

  def destroy
    @idea.images.destroy_all
    @idea.destroy
    flash[:success] = "Idea Deleted"
    redirect_to user_ideas_path(current_user)
  end

  private

  def idea_params
    params.require(:idea).permit(:title, :content, :user, :category_id)
  end

  def which_user
    @user = current_user
  end

  def which_idea
    @idea = Idea.find(params[:id])
  end

  def set_images
    @idea.images << params[:images].map { |f| Image.find(f) }
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by(username: params[:username])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      flash[:success] = "Successfully logged in."
      redirect_to user_path(user)
    else
      flash[:error] = "Incorrect username or password. Try again."
      render :new
    end
  end

  def destroy
    session.destroy
    flash[:success] = "Successfully logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      session[:user_id] = @user.id
      flash[:success] = "Account created."
      redirect_to user_path(@user)
    else
      flash[:error] = "Username already exists. Log in or choose another."
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
    unless @user == current_user
      flash[:error] = "Must be logged in to continue."
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
    if current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/categories/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>Edit this <%= @category.title %> here. </h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <%= form_for [:admin, @category] do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/admin/categories/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Create a new Category", new_admin_category_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>All Categories</h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <ul>
      <% @categories.each do |category| %>
        <li><%= link_to category.title, admin_category_path(category) %></li>
        <%= link_to "Edit", edit_admin_category_path(category) %>
        <%= link_to "Delete", admin_category_path(category), method: :delete %> <br> <br>
      <% end %>
    </ul>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/admin/categories/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>Welcome, <%= @user.username %></h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <%= form_for [:admin, @category] do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/admin/categories/show.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>All Ideas for <%= @category.title %></h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <% @category.ideas.each do |idea| %>
      <ul><%= link_to idea.title, idea_path(idea) %></ul>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/admin/images/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>Edit this Image here.</h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <%= form_for [:admin, @image] do |f| %>
      <%= f.label :url %>
      <%= f.text_field :url %>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/admin/images/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "Add a new Image", new_admin_image_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>All Images</h2>
    <p>Click links to right of an image to Edit or Delete it.</p>
    <br><br>
  </div>

  <div class="image-index">
    <% @images.each do |image| %>
      <img src="<%= image.url %>" width='300'>
      <%= link_to "Edit", edit_admin_image_path(image) %>
      <%= link_to "Delete", admin_image_path(image), method: :delete %>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/admin/images/new.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>Enter a new Idea here</h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <%= form_for [:admin, @image] do |f| %>
      <%= f.label :url %>
      <%= f.text_field :url %>
      <%= f.submit %>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/ideas/create.html.erb
<h1>Ideas#create</h1>
<p>Find me in app/views/ideas/create.html.erb</p>

app/views/ideas/destroy.html.erb
<h1>Ideas#destroy</h1>
<p>Find me in app/views/ideas/destroy.html.erb</p>

app/views/ideas/edit.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>Enter a new Idea here</h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <%= form_for @idea do |f| %>
      <%= f.label :title %>
      <%= f.text_field :title %>
      <%= f.label :content %>
      <%= f.text_area :content %>
      <%= f.label :category_id %>
      <%= f.collection_select(:category_id, Category.order(:title), :id, :title) %>
      <%= f.submit %> <br>
      <%= f.label "Add images by clicking check boxes below." %>
      <div id="image-box">
        <% Image.all.each do |image| %>
          <%= check_box_tag "images[]", image.id %>
          <%= image_tag image.url %>
        <% end %>
      </div>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/ideas/index.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title>IdeaBox</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>

<div class="container-fluid">
  <div class="row content">
    <div class="col-sm-3 sidenav">
      <h4>IdeaBox</h4>
      <ul class="nav nav-pills nav-stacked">
        <li class="active"><%= link_to "Home", user_path(@user) %></li>
        <li><%= link_to "Categories", admin_categories_path if current_user.admin? %></li>
        <li><%= link_to "Images", admin_images_path if current_user.admin? %></li>
        <li><%= link_to "My Ideas", user_ideas_path(@user) %></li>
        <li><%= link_to "Create a new Idea", new_user_idea_path(@user) %></li>
        <li><%= link_to "Log Out", logout_path, method: :delete %></li>
      </ul><br>
      <div class="input-group">
          </button>
        </span>
      </div>
    </div>

  <div class="col-sm-9">
    <h4></h4>
    <hr>
    <h2>My Ideas</h2>
    <p></p>
    <br><br>
  </div>

  <div class="forms">
    <% @ideas.each do |idea| %>
    <ul class="idea_<%= idea.id %>">
        <li><%= link_to idea.title, idea_path(idea) %></li>
        <li><%= idea.content %></li>
        <%= link_to "Edit", edit_idea_path(idea) %>
        <%= link_to "Delete", idea_path(idea), method: :delete %>
    </ul>
    <% end %>
  </div>

  <div class="body-image">
    <!-- <img src="https://research.rpi.edu/sites/default/files/styles/front_page/public/banner-IDEA.jpg?itok=9zGzrBlk" alt=""> -->
  </div>

<footer class="container-fluid">
  <p>© 2018 Cameron Johnson</p>
</footer>

</body>
</html>

app/views/ideas/update.html.erb
<h1>Ideas#update</h1>
<p>Find me in app/views/ideas/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IdeaBox</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <% if flash.keys.first == "success" %>
      <div class="flash-success">
        <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
        <% end %>
      </div>
    <% elsif flash.keys.first == "error" %>
      <div class="flash-error">
        <% flash.each do |name, msg| %>
        <%= content_tag :div, msg, class: name %>
        <% end %>
      </div>
    <% end %>
    <%= yield %>
  </body>
</html>